language: go
go:
- 1.4.3
install:
- sudo apt-get install make libgtk-3-dev libappindicator3-dev -y
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
script:
- openssl aes-256-cbc -K $encrypted_f217260732a9_key -iv $encrypted_f217260732a9_iv
  -in envvars.bash.enc -out envvars.bash -d
- make test-and-cover
after_success:
- GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
before_install:
- openssl aes-256-cbc -K $encrypted_f217260732a9_key -iv $encrypted_f217260732a9_iv
  -in envvars.bash.enc -out envvars.bash -d
