name: lantern
description: Lantern
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # paths
  path: ^1.9.1
  path_provider: ^2.1.5
  #Routing
  auto_route: ^9.3.0+1
  #UI Utils
  animated_toggle_switch: ^0.8.4
  animated_text_kit: ^4.2.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  device_preview_plus: ^2.3.0
  #Localization
  i18n_extension: ^15.0.4
  i18n_extension_importer: ^0.0.6
  intl: ^0.19.0
  #Images
  flutter_svg: ^2.0.17
  # Logs
  flutter_loggy: ^2.0.3+1
  loggy: ^2.0.3
  # Local DB
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  #FFI gen
  ffi: ^2.1.4
  #State management
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.3.3
  # dependency injection
  get_it: ^8.0.3
  #fonts
  google_fonts: ^6.2.1
  #env
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  # share
  share_plus: ^10.1.4
  #native
#  flutter_native_splash: ^2.4.5
  sentry_flutter: ^9.0.0-alpha.1
  # Deeplink handling
  app_links: ^6.4.0
  # Desktop
  window_manager: ^0.4.3
  tray_manager: ^0.3.2
  win32_registry: ^1.1.5
  # Utils
  fpdart: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.15
  objectbox_generator: 4.1.0
  riverpod_generator: ^2.3.3

  riverpod_lint: ^2.3.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/locales/
    - app.env


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: core/services/db
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other
