language: go
go:
- 1.5.1
install:
- go get golang.org/x/tools/cmd/cover
- go get -v github.com/axw/gocov/gocov
- go get -v github.com/mattn/goveralls
- go get -t
script:
- GOPATH=`pwd`:$GOPATH; go test -v -covermode=count -coverprofile=profile_tmp github.com/getlantern/http-proxy && tail -n +2 profile_tmp >> profile.cov && tail -n +2 profile_tmp >> profile.cov
after_success:
- GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
